# Generated by Django 5.1.1 on 2024-09-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_business_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='owner',
        ),
    ]
