# Generated by Django 5.1.1 on 2024-09-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_business_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default='business_images/default.png', upload_to='business_images/'),
        ),
    ]
