# Generated by Django 5.1.1 on 2024-09-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_business_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='business_images/default.png', upload_to='business_images/'),
        ),
    ]
